import "./globals.css";
import { Overpass } from "next/font/google";

export const metadata = {
  title: "Tabela Periódica",
  description: "Generated by create next app",
};

const font = Overpass({
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
